### ISSUE TITLE
sensors_data endpoint not well documented

### ISSUE THREAD

**Issue by cdupont** [Waziup/waziup.io-old#14]
Currently, the sensors_data is not documented.

**Comment by skngetich** [comment]
I found out using the `curl -X GET "https://api.waziup.io/api/v2/devices/MyDevice/sensors" -H "accept: application/json"` gave me all the sensors on the device and the latest data. This however has not been indicated in the documentation.

The current documentation show reading for a single sensor using this endpoint ` curl -X GET "https://api.waziup.io/api/v2/devices/MyDevice/sensors/TC" -H "accept: application/json" `

I would be be helpful to add this on the documentation.

**Comment by cdupont** [comment]
Hi Stephen, thanks for the heads up!
How to get the list of sensors is documented here: https://www.waziup.io/documentation/wazicloud/api/v2/#read-a-particular-device
This should return the list of sensors.
I also updated the documentation for the `sensors_data` endpoint: https://www.waziup.io/documentation/wazicloud/api/v2/#datapoints

This website also documents the full API: https://api.waziup.io/docs
